before_script:
  - carthage bootstrap

stages:
  - build
 
build_project:
  stage: build
  script:
    - xcodebuild clean -project NoMADLogin-AD.xcodeproj -scheme NoMADLoginAD | xcpretty
    - xcodebuild  -project NoMADLogin-AD.xcodeproj -scheme NoMADLoginAD | xcpretty -s
  artifacts:
    untracked: true
